### PR TITLE
Add support for username and password in ActiveMQ connection

### PR DESCRIPTION
**Pull request by albanf**
This adds the possibility the specify username and password for the ActiveMQ connection in the graylog configuration.

### CODE REVIEW

**Comment by exabrial** [comment]
This project uses Tabs not Spaces! Take look at the formatting and try to match. If you get that all fixed I'll merge and release! THANK YOU!

**Comment by albanf** [comment]
I've fixed the formatting, thanks :)

**Comment by exabrial** [comment]
This looks great. I'll review tonight merge/release. Thank you!

**Comment by albanf** [comment]
Hi, will you have time to review and merge soon? Thanks.

**Comment by exabrial** [comment]
Here you go :) I merged your other PR on the logback side but forgot about this one. Release is running now

**Comment by albanf** [comment]
Thanks!

**Pull request merged**
